grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.local
  persistence:
    enabled: true
    size: 1Gi
  
nodeExporter:
  enabled: true

prometheus-node-exporter:
  enabled: true
  prometheus:
    monitor:
      relabelings:
        - sourceLabels:
          - __meta_kubernetes_pod_node_name
          separator: ;
          regex: (.+)
          targetLabel: instance
          replacement: $1
          action: replace

prometheus:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.local
  prometheusSpec:
    retention: 365d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

