{
 "title": "ScheduleSync API",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "route", "query": { "query": "label_values(route)" } },
   { "name": "status_code", "query": { "query": "label_values(status_code)" } },
   { "name": "method", "query": { "query": "label_values(method)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{route=~\"$route\", status_code=~\"$status_code\", method=~\"$method\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "90th percentile response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_milliseconds_bucket{route=~\"$route\", status_code=~\"$status_code\", method=~\"$method\"}[1m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "AVG Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_milliseconds_sum{route=~\"$route\", status_code=~\"$status_code\", method=~\"$method\"}[1m]) / rate(http_request_duration_milliseconds_count{route=~\"$route\", status_code=~\"$status_code\", method=~\"$method\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}