apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus-community/kube-prometheus-stack
    targetRevision: 58.2.2
    helm:
      valueFiles:
      - $values/infrastructure/helm-values/kube-prometheus-stack/values.yaml
  - repoURL: 'https://github.com/missaelcorm-iteso/schedulesync-devops.git'
    targetRevision: main
    ref: values
  - repoURL: https://github.com/missaelcorm-iteso/schedulesync-devops
    path: kubernetes/prometheus/manifests
    targetRevision: main