apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedulesync-api
  namespace: schedulesync-api
  labels:
    app: schedulesync-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: schedulesync-api
  template:
    metadata:
      labels:
        app: schedulesync-api
    spec:
      containers:
        - name: schedulesync-api
          image: missaelcorm/schedulesync-api:v0.11
          env:
            - name:  MONGO_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name:  schedulesync-api
                  key:  MONGO_PROTOCOL
            - name:  MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name:  schedulesync-api
                  key:  MONGO_HOST
            - name:  MONGO_DB
              valueFrom:
                secretKeyRef:
                  name:  schedulesync-api
                  key:  MONGO_DB
            - name:  MONGO_USER
              valueFrom:
                secretKeyRef:
                  name:  schedulesync-api
                  key:  MONGO_USER
            - name:  MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name:  schedulesync-api
                  key:  MONGO_PASS
            - name:  APP_PORT
              valueFrom:
                secretKeyRef:
                  name:  schedulesync-api
                  key:  APP_PORT
            - name:  SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name:  schedulesync-api
                  key:  SECRET_KEY
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
