apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: schedulesync-api
    release: kube-prometheus-stack
  name: schedulesync-api
  namespace: schedulesync-api
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      app: schedulesync-api