services:
  schedulesync-api:
    image: schedulesync-api:latest
    container_name: schedulesync-api
    ports:
      - 5000:3000
    volumes:
      - ./.env:/usr/src/app/.env

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-storage: